export default {
	POST_CHIRP_REQUEST: 'POST_CHIRP_REQUEST',
	POST_CHIRP_SUCCESS: 'POST_CHIRP_SUCCESS',

	FETCH_CHIRPS_REQUEST: 'FETCH_CHIRPS_REQUEST',
	FETCH_CHIRPS_SUCCESS: 'FETCH_CHIRPS_SUCCESS',

	FETCH_USERS_REQUEST: 'FETCH_USERS_REQUEST',
	FETCH_USERS_SUCCESS: 'FETCH_USERS_SUCCESS',

	FOLLOW: 'FOLLOW',
	FOLLOWED: 'FOLLOWED',

	UNFOLLOW: 'UNFOLLOW',
	UNFOLLOWED: 'UNFOLLOWED'

};